### ISSUE TITLE
Getting started? Example?

### ISSUE THREAD

**Issue by p-brz** [DavidKeller/kademlia#1]
Hello!

I have found your library and wanna give a try (i am looking for dht libraries).
Despite the README saying that it is still experimental, i liked the code style and saw that it has many tests.

So, are there some example or anything to help get started?
Besides the code fragments on README?
Also, are there some DHT networking running it, to help bootstrap nodes?
Or anything compatible?

Thanks!

**Comment by DavidKeller** [comment]
Hi !

I marked it experimental as it is missing a good stress test tool beside unit tests to ensure library is working in all cases.

Public API is not even frozen, as I'm considering moving from a session::run() method to a session::run_one() and session::poll_one() allowing mono-threaded applications to call kademlia event loop inside their own event loop.

Documentation will come after theses.

Meanwhile, you can still play with it, creating a [first_session](https://github.com/DavidKeller/kademlia/blob/master/include/kademlia/first_session.hpp#L46) to bootstrap, and then some [sessions](https://github.com/DavidKeller/kademlia/blob/master/include/kademlia/session.hpp#L46) to store and load data.

If you feel that something is missing, feel free to create a feature request. But to be honest, I won't have spare time to work on it before 3 months.

**Comment by paulobrizolara** [comment]
Nice.

When i saw *experimental*, i was afraid that something could not been working. :)

About freezing the API or documentation, don't worry. I was looking more for a running example.
But i think i can figure out. The API is really simple!

Nice work!  :+1:

**Comment by DavidKeller** [comment]
https://kademlia-cpp.readthedocs.io/en/latest/?badge=master
