### ISSUE TITLE
Incompatible Protocol

### ISSUE THREAD

**Issue by metellica** [DavidKeller/kademlia#2]
Hi, I happened to try your codes(both library and example), but it seems to be incompatible with the Mainline DHT network of BitTorrent, is that true?

**Comment by DavidKeller** [comment]
Hello, yes both DHT implementations are incompatible.
It seems unlikely that they will become compatible in a near future.

Why don't you use one of the Mainline DHT implementations directly ?

**Comment by metellica** [comment]
Thanks for your quick response and yes, I will give libtorrent a try.
