### ISSUE TITLE
Can it be compiled on Windows operating system？

### ISSUE THREAD

**Issue by Zjek** [DavidKeller/kademlia#6]
Hello!
I want to learn about this project. I have cmake, but I can't take the next step.

Compiling environment：vs2019

Thanks！

**Comment by DavidKeller** [comment]
Hello,

Yes ! https://ci.appveyor.com/project/DavidKeller/kademlia
So command line build is tested.

That being said, I'm not aware of the Visual Studio GUI build status.
https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-160

Please keep me updated if you face any difficulty.

**Comment by Zjek** [comment]
Hello,@DavidKeller! 

I have complied it in your way.
How to start? Do you have detailed documentation？

Thanks！

**Comment by DavidKeller** [comment]
The [README](https://github.com/DavidKeller/kademlia/blob/master/README.md) contains an example.
