### ISSUE TITLE
Both notify_peer_task and lookup_task have in flight counters

### ISSUE THREAD

**Issue by aleks-f** [DavidKeller/kademlia#9]
[notify_peer_task](https://github.com/DavidKeller/kademlia/blob/master/src/kademlia/notify_peer_task.hpp#L46) inherits from lookup_task, yet each of these classes has its own `in_flight_requests_count_`. 

Is that on purpose? If it is, what is the reason?

**Comment by DavidKeller** [comment]
Hi Aleksandar, good catch !

I've written this [quick fix]( https://github.com/DavidKeller/kademlia/commit/4fb1645164b416deb22df6e679ec9279ce73410d), I'll push it to master later this week, after a look at the Travis failures.

**Comment by DavidKeller** [comment]
Merged to master.
